---
# Experiment IDs to copy from production to staging to be tested
experiment-ids:
# NOTE: this experiments are disabled because currently they are not used in staging and it takes around 6 minutes to copy them.
# In the future, the list should be used only in production to launch analysis for each of them.
# experiments used launch analysis on
# - 2093e95fd17372fb558b81b9142f230e # PBMC 10k
# - 06e7f90e7ea19eb773bfc95ef87fcc9e # Multisample murine
# - deb7b03bbfc0c96b448a1d4f595f75fe # Seth Coffelt gamma-delta T-cells: 8 samples dataset
# - f6e0613002157d3855ebf616f43c52bd # Seth Ryth Jones Edinburgh: 4 samples dataset
# - a13b9c0367134a964450ac8e91336cfb # David Waxman: Very big dataset
# experiment used to test launch analysis & metadata / species
- 135423f2b1009aa753b0535168364860 # Metadata test