name: Run end-to-end tests

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to run the tests on (staging, production)'
        required: false
        default: 'production'
  schedule:
    - cron:  '22 2 * * *'

jobs:
  run-e2e:
    name: ${{ format('Run e2e tests for {0}', github.event.inputs.environment || 'production') }}
    runs-on: ubuntu-20.04
    steps:
      - id: checkout
        name: Check out source code
        uses: actions/checkout@v2

      - id: checkout-biomage-utils
        name: Check out Biomage utils
        uses: actions/checkout@v2
        with:
          repository: 'biomage/biomage-utils'
          path: 'biomage-utils'

      - id: setup-biomage-utils
        name: Setup Biomage utils
        run: |-
          cd biomage-utils/
          make install
          make test

      - id: setup-aws
        name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - id: install-yq-jq
        name: Install yq and jq to parse config file
        run: |-
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CC86BB64
          sudo add-apt-repository ppa:rmescandon/yq
          sudo apt update
          sudo apt install yq -y
          sudo apt-get install jq -y

      - id: copy-experiments
        name: Copy experiments
        run: |-
          cd biomage-utils/
          for EXP_ID in $(yq e '.experiment-ids' ../config.yaml -j | jq '.[]')
          do
            biomage experiment copy -e $EXP_ID
          done

      - id: install
        name: Install dependencies
        run: |-
          cd e2e/
          git config --global url."https://".insteadOf ssh://
          npm ci

      - id: test
        name: Run e2e tests
        run: |-
          cd e2e/
          K8S_ENV=${{ github.event.inputs.environment || 'production' }} npm start
        env:
          CYPRESS_E2E_USERNAME: ${{ secrets.CYPRESS_E2E_USERNAME }}
          CYPRESS_E2E_PASSWORD: ${{ secrets.CYPRESS_E2E_PASSWORD }}

      - id: send-to-slack
        name: Send failure notification to Slack
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.BUILD_STATUS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: pipelines
          status: FAILED
          color: danger
