name: Run end-to-end tests

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to run the tests on (staging, production)'
        required: false
        default: 'production'
  schedule:
    - cron:  '22 2 * * *'

jobs:
  run-e2e:
    name: ${{ format('Run e2e tests for {0}', github.event.inputs.environment || 'production') }}
    runs-on: ubuntu-20.04
    steps:
      - id: checkout
        name: Check out source code
        uses: actions/checkout@v2

      - id: install
        name: Install dependencies
        run: |-
          cd e2e/
          git config --global url."https://".insteadOf ssh://
          npm ci

      - id: test
        name: Run e2e tests
        run: |-
          cd e2e/
          K8S_ENV=${{ github.event.inputs.environment || 'production' }} npm start

      - id: send-to-slack
        name: Send failure notification to Slack
        if: failure() && github.event_name == 'push'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.BUILD_STATUS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: pipelines
          status: FAILED
          color: danger