name: Run end-to-end tests

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to run the tests on (staging, production)'
        required: false
        default: 'production'
  schedule:
    # * is a special character in YAML so you have to quote this string
    # - cron:  '0 0 * * *'
    - cron:  '*/5 * * * *'

jobs:
  run-e2e:
    name: ${{ format('Run e2e tests for {0}', github.event.inputs.environment) }}
    runs-on: ubuntu-20.04
    steps:
      - id: checkout
        name: Check out source code
        uses: actions/checkout@v2

      - id: install
        name: Install dependencies
        run: |-
          cd e2e/
          git config --global url."https://".insteadOf ssh://
          npm ci

      - id: test
        name: Run e2e tests
        run: |-
          cd e2e/
          K8S_ENV=${{ github.event.inputs.environment }} npm start
